[package]
name = "tsrzl"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "A Rust implementation of a TypeScript compiler"
license = "Apache-2.0"
repository = "https://github.com/tsrzl/compiler"
readme = "README.md"
autobenches = false

[lib]
bench = false

[dev-dependencies]
cntryl-stress = "0.5.1"

[[bench]]
name = "compiler"
path = "benches/compiler.rs"
harness = false
