// Code generated by scripts/generate-ast.ts from TypeScript-Go 2bd066d87f5bafd315be9f40889d0a60b9e58e0b. DO NOT EDIT.

use super::SyntaxKind;

impl SyntaxKind {
    /// Returns whether the kind belongs to TypeScript-Go's `TriviaSyntaxKind`.
    #[must_use]
    pub fn is_trivia_kind(self) -> bool {
        matches!(
            self,
            Self::SingleLineCommentTrivia
                | Self::MultiLineCommentTrivia
                | Self::NewLineTrivia
                | Self::WhitespaceTrivia
                | Self::ConflictMarkerTrivia
        )
    }

    /// Returns whether the kind belongs to TypeScript-Go's `LiteralSyntaxKind`.
    #[must_use]
    pub fn is_literal_kind(self) -> bool {
        (Self::FIRST_LITERAL_TOKEN..=Self::LAST_LITERAL_TOKEN).contains(&self)
    }

    /// Returns whether the kind belongs to TypeScript-Go's `PseudoLiteralSyntaxKind`.
    #[must_use]
    pub fn is_pseudo_literal_kind(self) -> bool {
        matches!(
            self,
            Self::TemplateHead | Self::TemplateMiddle | Self::TemplateTail
        )
    }

    /// Returns whether the kind belongs to TypeScript-Go's `PunctuationSyntaxKind`.
    #[must_use]
    pub fn is_punctuation_kind(self) -> bool {
        (Self::FIRST_PUNCTUATION..=Self::LAST_PUNCTUATION).contains(&self)
    }

    /// Returns whether the kind belongs to TypeScript-Go's `KeywordSyntaxKind`.
    #[must_use]
    pub fn is_keyword_kind(self) -> bool {
        (Self::FIRST_KEYWORD..=Self::LAST_KEYWORD).contains(&self)
    }

    /// Returns whether the kind belongs to TypeScript-Go's `ModifierSyntaxKind`.
    #[must_use]
    pub fn is_modifier_kind(self) -> bool {
        matches!(
            self,
            Self::AbstractKeyword
                | Self::AccessorKeyword
                | Self::AsyncKeyword
                | Self::ConstKeyword
                | Self::DeclareKeyword
                | Self::DefaultKeyword
                | Self::ExportKeyword
                | Self::InKeyword
                | Self::PrivateKeyword
                | Self::ProtectedKeyword
                | Self::PublicKeyword
                | Self::ReadonlyKeyword
                | Self::OutKeyword
                | Self::OverrideKeyword
                | Self::StaticKeyword
        )
    }

    /// Returns whether the kind belongs to TypeScript-Go's `KeywordTypeSyntaxKind`.
    #[must_use]
    pub fn is_keyword_type_kind(self) -> bool {
        matches!(
            self,
            Self::AnyKeyword
                | Self::BigIntKeyword
                | Self::BooleanKeyword
                | Self::IntrinsicKeyword
                | Self::NeverKeyword
                | Self::NumberKeyword
                | Self::ObjectKeyword
                | Self::StringKeyword
                | Self::SymbolKeyword
                | Self::UndefinedKeyword
                | Self::UnknownKeyword
                | Self::VoidKeyword
        )
    }

    /// Returns whether the kind belongs to TypeScript-Go's `KeywordExpressionSyntaxKind`.
    #[must_use]
    pub fn is_keyword_expression_kind(self) -> bool {
        matches!(
            self,
            Self::NullKeyword
                | Self::TrueKeyword
                | Self::FalseKeyword
                | Self::ThisKeyword
                | Self::SuperKeyword
                | Self::ImportKeyword
        )
    }

    /// Returns whether the kind belongs to TypeScript-Go's `TokenSyntaxKind`.
    #[must_use]
    pub fn is_token_kind(self) -> bool {
        (Self::FIRST_TOKEN..=Self::LAST_TOKEN).contains(&self)
    }

    /// Returns whether the kind belongs to TypeScript-Go's `JsxTokenSyntaxKind`.
    #[must_use]
    pub fn is_jsx_token_kind(self) -> bool {
        matches!(
            self,
            Self::LessThanSlashToken
                | Self::EndOfFile
                | Self::ConflictMarkerTrivia
                | Self::JsxText
                | Self::JsxTextAllWhiteSpaces
                | Self::OpenBraceToken
                | Self::LessThanToken
        )
    }

    /// Returns whether the kind belongs to TypeScript-Go's `JSDocNodeSyntaxKind`.
    #[must_use]
    pub fn is_jsdoc_node_kind(self) -> bool {
        (Self::FIRST_JSDOC_NODE..=Self::LAST_JSDOC_NODE).contains(&self)
    }

    /// Returns whether the kind belongs to TypeScript-Go's `ImportPhaseModifierSyntaxKind`.
    #[must_use]
    pub fn is_import_phase_modifier_kind(self) -> bool {
        matches!(self, Self::TypeKeyword | Self::DeferKeyword)
    }

    /// Returns whether the kind belongs to TypeScript-Go's `PostfixUnaryOperator`.
    #[must_use]
    pub fn is_postfix_unary_operator(self) -> bool {
        matches!(self, Self::PlusPlusToken | Self::MinusMinusToken)
    }

    /// Returns whether the kind belongs to TypeScript-Go's `PrefixUnaryOperator`.
    #[must_use]
    pub fn is_prefix_unary_operator(self) -> bool {
        matches!(
            self,
            Self::PlusToken
                | Self::MinusToken
                | Self::TildeToken
                | Self::ExclamationToken
                | Self::PlusPlusToken
                | Self::MinusMinusToken
        )
    }

    /// Returns whether the kind belongs to TypeScript-Go's `AssignmentOperator`.
    #[must_use]
    pub fn is_assignment_operator(self) -> bool {
        matches!(self, Self::EqualsToken) || self.is_compound_assignment_operator()
    }

    /// Returns whether the kind belongs to TypeScript-Go's `BinaryOperator`.
    #[must_use]
    pub fn is_binary_operator(self) -> bool {
        matches!(self, Self::CommaToken) || self.is_assignment_operator_or_higher()
    }

    /// Returns whether the kind belongs to TypeScript-Go's `ExponentiationOperator`.
    #[must_use]
    pub fn is_exponentiation_operator(self) -> bool {
        matches!(self, Self::AsteriskAsteriskToken)
    }

    /// Returns whether the kind belongs to TypeScript-Go's `MultiplicativeOperator`.
    #[must_use]
    pub fn is_multiplicative_operator(self) -> bool {
        matches!(
            self,
            Self::AsteriskToken | Self::SlashToken | Self::PercentToken
        )
    }

    /// Returns whether the kind belongs to TypeScript-Go's `MultiplicativeOperatorOrHigher`.
    #[must_use]
    pub fn is_multiplicative_operator_or_higher(self) -> bool {
        self.is_exponentiation_operator() || self.is_multiplicative_operator()
    }

    /// Returns whether the kind belongs to TypeScript-Go's `AdditiveOperator`.
    #[must_use]
    pub fn is_additive_operator(self) -> bool {
        matches!(self, Self::PlusToken | Self::MinusToken)
    }

    /// Returns whether the kind belongs to TypeScript-Go's `AdditiveOperatorOrHigher`.
    #[must_use]
    pub fn is_additive_operator_or_higher(self) -> bool {
        self.is_multiplicative_operator_or_higher() || self.is_additive_operator()
    }

    /// Returns whether the kind belongs to TypeScript-Go's `ShiftOperator`.
    #[must_use]
    pub fn is_shift_operator(self) -> bool {
        matches!(
            self,
            Self::LessThanLessThanToken
                | Self::GreaterThanGreaterThanToken
                | Self::GreaterThanGreaterThanGreaterThanToken
        )
    }

    /// Returns whether the kind belongs to TypeScript-Go's `ShiftOperatorOrHigher`.
    #[must_use]
    pub fn is_shift_operator_or_higher(self) -> bool {
        self.is_additive_operator_or_higher() || self.is_shift_operator()
    }

    /// Returns whether the kind belongs to TypeScript-Go's `RelationalOperator`.
    #[must_use]
    pub fn is_relational_operator(self) -> bool {
        matches!(
            self,
            Self::LessThanToken
                | Self::LessThanEqualsToken
                | Self::GreaterThanToken
                | Self::GreaterThanEqualsToken
                | Self::InstanceOfKeyword
                | Self::InKeyword
        )
    }

    /// Returns whether the kind belongs to TypeScript-Go's `RelationalOperatorOrHigher`.
    #[must_use]
    pub fn is_relational_operator_or_higher(self) -> bool {
        self.is_shift_operator_or_higher() || self.is_relational_operator()
    }

    /// Returns whether the kind belongs to TypeScript-Go's `EqualityOperator`.
    #[must_use]
    pub fn is_equality_operator(self) -> bool {
        matches!(
            self,
            Self::EqualsEqualsToken
                | Self::EqualsEqualsEqualsToken
                | Self::ExclamationEqualsEqualsToken
                | Self::ExclamationEqualsToken
        )
    }

    /// Returns whether the kind belongs to TypeScript-Go's `EqualityOperatorOrHigher`.
    #[must_use]
    pub fn is_equality_operator_or_higher(self) -> bool {
        self.is_relational_operator_or_higher() || self.is_equality_operator()
    }

    /// Returns whether the kind belongs to TypeScript-Go's `BitwiseOperator`.
    #[must_use]
    pub fn is_bitwise_operator(self) -> bool {
        matches!(
            self,
            Self::AmpersandToken | Self::BarToken | Self::CaretToken
        )
    }

    /// Returns whether the kind belongs to TypeScript-Go's `BitwiseOperatorOrHigher`.
    #[must_use]
    pub fn is_bitwise_operator_or_higher(self) -> bool {
        self.is_equality_operator_or_higher() || self.is_bitwise_operator()
    }

    /// Returns whether the kind belongs to TypeScript-Go's `LogicalOperator`.
    #[must_use]
    pub fn is_logical_operator(self) -> bool {
        matches!(self, Self::AmpersandAmpersandToken | Self::BarBarToken)
    }

    /// Returns whether the kind belongs to TypeScript-Go's `LogicalOperatorOrHigher`.
    #[must_use]
    pub fn is_logical_operator_or_higher(self) -> bool {
        self.is_bitwise_operator_or_higher() || self.is_logical_operator()
    }

    /// Returns whether the kind belongs to TypeScript-Go's `CompoundAssignmentOperator`.
    #[must_use]
    pub fn is_compound_assignment_operator(self) -> bool {
        matches!(
            self,
            Self::PlusEqualsToken
                | Self::MinusEqualsToken
                | Self::AsteriskAsteriskEqualsToken
                | Self::AsteriskEqualsToken
                | Self::SlashEqualsToken
                | Self::PercentEqualsToken
                | Self::AmpersandEqualsToken
                | Self::BarEqualsToken
                | Self::CaretEqualsToken
                | Self::LessThanLessThanEqualsToken
                | Self::GreaterThanGreaterThanGreaterThanEqualsToken
                | Self::GreaterThanGreaterThanEqualsToken
                | Self::BarBarEqualsToken
                | Self::AmpersandAmpersandEqualsToken
                | Self::QuestionQuestionEqualsToken
        )
    }

    /// Returns whether the kind belongs to TypeScript-Go's `AssignmentOperatorOrHigher`.
    #[must_use]
    pub fn is_assignment_operator_or_higher(self) -> bool {
        matches!(self, Self::QuestionQuestionToken)
            || self.is_logical_operator_or_higher()
            || self.is_assignment_operator()
    }

    /// Returns whether the kind belongs to TypeScript-Go's `LogicalOrCoalescingAssignmentOperator`.
    #[must_use]
    pub fn is_logical_or_coalescing_assignment_operator(self) -> bool {
        matches!(
            self,
            Self::AmpersandAmpersandEqualsToken
                | Self::BarBarEqualsToken
                | Self::QuestionQuestionEqualsToken
        )
    }
}
