//! Keyword lookup, matching TypeScript-Go's `textToKeyword` table.

use crate::ast::SyntaxKind;

/// Returns the keyword kind spelled by `text`, or [`SyntaxKind::Identifier`].
#[must_use]
pub fn identifier_token(text: &str) -> SyntaxKind {
    if !(2..=12).contains(&text.len()) || !text.as_bytes()[0].is_ascii_lowercase() {
        return SyntaxKind::Identifier;
    }
    keyword(text).unwrap_or(SyntaxKind::Identifier)
}

/// Returns the keyword kind spelled by `text`, if any.
#[must_use]
pub fn keyword(text: &str) -> Option<SyntaxKind> {
    Some(match text {
        "abstract" => SyntaxKind::AbstractKeyword,
        "accessor" => SyntaxKind::AccessorKeyword,
        "any" => SyntaxKind::AnyKeyword,
        "as" => SyntaxKind::AsKeyword,
        "assert" => SyntaxKind::AssertKeyword,
        "asserts" => SyntaxKind::AssertsKeyword,
        "async" => SyntaxKind::AsyncKeyword,
        "await" => SyntaxKind::AwaitKeyword,
        "bigint" => SyntaxKind::BigIntKeyword,
        "boolean" => SyntaxKind::BooleanKeyword,
        "break" => SyntaxKind::BreakKeyword,
        "case" => SyntaxKind::CaseKeyword,
        "catch" => SyntaxKind::CatchKeyword,
        "class" => SyntaxKind::ClassKeyword,
        "const" => SyntaxKind::ConstKeyword,
        "constructor" => SyntaxKind::ConstructorKeyword,
        "continue" => SyntaxKind::ContinueKeyword,
        "debugger" => SyntaxKind::DebuggerKeyword,
        "declare" => SyntaxKind::DeclareKeyword,
        "default" => SyntaxKind::DefaultKeyword,
        "defer" => SyntaxKind::DeferKeyword,
        "delete" => SyntaxKind::DeleteKeyword,
        "do" => SyntaxKind::DoKeyword,
        "else" => SyntaxKind::ElseKeyword,
        "enum" => SyntaxKind::EnumKeyword,
        "export" => SyntaxKind::ExportKeyword,
        "extends" => SyntaxKind::ExtendsKeyword,
        "false" => SyntaxKind::FalseKeyword,
        "finally" => SyntaxKind::FinallyKeyword,
        "for" => SyntaxKind::ForKeyword,
        "from" => SyntaxKind::FromKeyword,
        "function" => SyntaxKind::FunctionKeyword,
        "get" => SyntaxKind::GetKeyword,
        "global" => SyntaxKind::GlobalKeyword,
        "if" => SyntaxKind::IfKeyword,
        "immediate" => SyntaxKind::ImmediateKeyword,
        "implements" => SyntaxKind::ImplementsKeyword,
        "import" => SyntaxKind::ImportKeyword,
        "in" => SyntaxKind::InKeyword,
        "infer" => SyntaxKind::InferKeyword,
        "instanceof" => SyntaxKind::InstanceOfKeyword,
        "interface" => SyntaxKind::InterfaceKeyword,
        "intrinsic" => SyntaxKind::IntrinsicKeyword,
        "is" => SyntaxKind::IsKeyword,
        "keyof" => SyntaxKind::KeyOfKeyword,
        "let" => SyntaxKind::LetKeyword,
        "module" => SyntaxKind::ModuleKeyword,
        "namespace" => SyntaxKind::NamespaceKeyword,
        "never" => SyntaxKind::NeverKeyword,
        "new" => SyntaxKind::NewKeyword,
        "null" => SyntaxKind::NullKeyword,
        "number" => SyntaxKind::NumberKeyword,
        "object" => SyntaxKind::ObjectKeyword,
        "of" => SyntaxKind::OfKeyword,
        "out" => SyntaxKind::OutKeyword,
        "override" => SyntaxKind::OverrideKeyword,
        "package" => SyntaxKind::PackageKeyword,
        "private" => SyntaxKind::PrivateKeyword,
        "protected" => SyntaxKind::ProtectedKeyword,
        "public" => SyntaxKind::PublicKeyword,
        "readonly" => SyntaxKind::ReadonlyKeyword,
        "require" => SyntaxKind::RequireKeyword,
        "return" => SyntaxKind::ReturnKeyword,
        "satisfies" => SyntaxKind::SatisfiesKeyword,
        "set" => SyntaxKind::SetKeyword,
        "static" => SyntaxKind::StaticKeyword,
        "string" => SyntaxKind::StringKeyword,
        "super" => SyntaxKind::SuperKeyword,
        "switch" => SyntaxKind::SwitchKeyword,
        "symbol" => SyntaxKind::SymbolKeyword,
        "this" => SyntaxKind::ThisKeyword,
        "throw" => SyntaxKind::ThrowKeyword,
        "true" => SyntaxKind::TrueKeyword,
        "try" => SyntaxKind::TryKeyword,
        "type" => SyntaxKind::TypeKeyword,
        "typeof" => SyntaxKind::TypeOfKeyword,
        "undefined" => SyntaxKind::UndefinedKeyword,
        "unique" => SyntaxKind::UniqueKeyword,
        "unknown" => SyntaxKind::UnknownKeyword,
        "using" => SyntaxKind::UsingKeyword,
        "var" => SyntaxKind::VarKeyword,
        "void" => SyntaxKind::VoidKeyword,
        "while" => SyntaxKind::WhileKeyword,
        "with" => SyntaxKind::WithKeyword,
        "yield" => SyntaxKind::YieldKeyword,
        _ => return None,
    })
}
