//! Keyword lookup, matching TypeScript-Go's `textToKeyword` table.

use crate::ast::SyntaxKind;

/// Returns the keyword kind spelled by `text`, or [`SyntaxKind::Identifier`].
#[must_use]
pub fn identifier_token(text: &str) -> SyntaxKind {
    if !(2..=12).contains(&text.len()) || !text.as_bytes()[0].is_ascii_lowercase() {
        return SyntaxKind::Identifier;
    }
    keyword(text).unwrap_or(SyntaxKind::Identifier)
}

/// Returns the keyword kind spelled by `text`, if any.
#[must_use]
pub fn keyword(text: &str) -> Option<SyntaxKind> {
    Some(match text {
        "abstract" => SyntaxKind::AbstractKeyword,
        "accessor" => SyntaxKind::AccessorKeyword,
        "any" => SyntaxKind::AnyKeyword,
        "as" => SyntaxKind::AsKeyword,
        "assert" => SyntaxKind::AssertKeyword,
        "asserts" => SyntaxKind::AssertsKeyword,
        "async" => SyntaxKind::AsyncKeyword,
        "await" => SyntaxKind::AwaitKeyword,
        "bigint" => SyntaxKind::BigIntKeyword,
        "boolean" => SyntaxKind::BooleanKeyword,
        "break" => SyntaxKind::BreakKeyword,
        "case" => SyntaxKind::CaseKeyword,
        "catch" => SyntaxKind::CatchKeyword,
        "class" => SyntaxKind::ClassKeyword,
        "const" => SyntaxKind::ConstKeyword,
        "constructor" => SyntaxKind::ConstructorKeyword,
        "continue" => SyntaxKind::ContinueKeyword,
        "debugger" => SyntaxKind::DebuggerKeyword,
        "declare" => SyntaxKind::DeclareKeyword,
        "default" => SyntaxKind::DefaultKeyword,
        "defer" => SyntaxKind::DeferKeyword,
        "delete" => SyntaxKind::DeleteKeyword,
        "do" => SyntaxKind::DoKeyword,
        "else" => SyntaxKind::ElseKeyword,
        "enum" => SyntaxKind::EnumKeyword,
        "export" => SyntaxKind::ExportKeyword,
        "extends" => SyntaxKind::ExtendsKeyword,
        "false" => SyntaxKind::FalseKeyword,
        "finally" => SyntaxKind::FinallyKeyword,
        "for" => SyntaxKind::ForKeyword,
        "from" => SyntaxKind::FromKeyword,
        "function" => SyntaxKind::FunctionKeyword,
        "get" => SyntaxKind::GetKeyword,
        "global" => SyntaxKind::GlobalKeyword,
        "if" => SyntaxKind::IfKeyword,
        "immediate" => SyntaxKind::ImmediateKeyword,
        "implements" => SyntaxKind::ImplementsKeyword,
        "import" => SyntaxKind::ImportKeyword,
        "in" => SyntaxKind::InKeyword,
        "infer" => SyntaxKind::InferKeyword,
        "instanceof" => SyntaxKind::InstanceOfKeyword,
        "interface" => SyntaxKind::InterfaceKeyword,
        "intrinsic" => SyntaxKind::IntrinsicKeyword,
        "is" => SyntaxKind::IsKeyword,
        "keyof" => SyntaxKind::KeyOfKeyword,
        "let" => SyntaxKind::LetKeyword,
        "module" => SyntaxKind::ModuleKeyword,
        "namespace" => SyntaxKind::NamespaceKeyword,
        "never" => SyntaxKind::NeverKeyword,
        "new" => SyntaxKind::NewKeyword,
        "null" => SyntaxKind::NullKeyword,
        "number" => SyntaxKind::NumberKeyword,
        "object" => SyntaxKind::ObjectKeyword,
        "of" => SyntaxKind::OfKeyword,
        "out" => SyntaxKind::OutKeyword,
        "override" => SyntaxKind::OverrideKeyword,
        "package" => SyntaxKind::PackageKeyword,
        "private" => SyntaxKind::PrivateKeyword,
        "protected" => SyntaxKind::ProtectedKeyword,
        "public" => SyntaxKind::PublicKeyword,
        "readonly" => SyntaxKind::ReadonlyKeyword,
        "require" => SyntaxKind::RequireKeyword,
        "return" => SyntaxKind::ReturnKeyword,
        "satisfies" => SyntaxKind::SatisfiesKeyword,
        "set" => SyntaxKind::SetKeyword,
        "static" => SyntaxKind::StaticKeyword,
        "string" => SyntaxKind::StringKeyword,
        "super" => SyntaxKind::SuperKeyword,
        "switch" => SyntaxKind::SwitchKeyword,
        "symbol" => SyntaxKind::SymbolKeyword,
        "this" => SyntaxKind::ThisKeyword,
        "throw" => SyntaxKind::ThrowKeyword,
        "true" => SyntaxKind::TrueKeyword,
        "try" => SyntaxKind::TryKeyword,
        "type" => SyntaxKind::TypeKeyword,
        "typeof" => SyntaxKind::TypeOfKeyword,
        "undefined" => SyntaxKind::UndefinedKeyword,
        "unique" => SyntaxKind::UniqueKeyword,
        "unknown" => SyntaxKind::UnknownKeyword,
        "using" => SyntaxKind::UsingKeyword,
        "var" => SyntaxKind::VarKeyword,
        "void" => SyntaxKind::VoidKeyword,
        "while" => SyntaxKind::WhileKeyword,
        "with" => SyntaxKind::WithKeyword,
        "yield" => SyntaxKind::YieldKeyword,
        _ => return None,
    })
}

/// Returns the source spelling of a punctuation or keyword token.
#[must_use]
pub fn token_to_string(kind: SyntaxKind) -> Option<&'static str> {
    Some(match kind {
        SyntaxKind::AbstractKeyword => "abstract",
        SyntaxKind::AccessorKeyword => "accessor",
        SyntaxKind::AmpersandAmpersandEqualsToken => "&&=",
        SyntaxKind::AmpersandAmpersandToken => "&&",
        SyntaxKind::AmpersandEqualsToken => "&=",
        SyntaxKind::AmpersandToken => "&",
        SyntaxKind::AnyKeyword => "any",
        SyntaxKind::AsKeyword => "as",
        SyntaxKind::AssertKeyword => "assert",
        SyntaxKind::AssertsKeyword => "asserts",
        SyntaxKind::AsteriskAsteriskEqualsToken => "**=",
        SyntaxKind::AsteriskAsteriskToken => "**",
        SyntaxKind::AsteriskEqualsToken => "*=",
        SyntaxKind::AsteriskToken => "*",
        SyntaxKind::AsyncKeyword => "async",
        SyntaxKind::AtToken => "@",
        SyntaxKind::AwaitKeyword => "await",
        SyntaxKind::BacktickToken => "`",
        SyntaxKind::BarBarEqualsToken => "||=",
        SyntaxKind::BarBarToken => "||",
        SyntaxKind::BarEqualsToken => "|=",
        SyntaxKind::BarToken => "|",
        SyntaxKind::BigIntKeyword => "bigint",
        SyntaxKind::BooleanKeyword => "boolean",
        SyntaxKind::BreakKeyword => "break",
        SyntaxKind::CaretEqualsToken => "^=",
        SyntaxKind::CaretToken => "^",
        SyntaxKind::CaseKeyword => "case",
        SyntaxKind::CatchKeyword => "catch",
        SyntaxKind::ClassKeyword => "class",
        SyntaxKind::CloseBraceToken => "}",
        SyntaxKind::CloseBracketToken => "]",
        SyntaxKind::CloseParenToken => ")",
        SyntaxKind::ColonToken => ":",
        SyntaxKind::CommaToken => ",",
        SyntaxKind::ConstKeyword => "const",
        SyntaxKind::ConstructorKeyword => "constructor",
        SyntaxKind::ContinueKeyword => "continue",
        SyntaxKind::DebuggerKeyword => "debugger",
        SyntaxKind::DeclareKeyword => "declare",
        SyntaxKind::DefaultKeyword => "default",
        SyntaxKind::DeferKeyword => "defer",
        SyntaxKind::DeleteKeyword => "delete",
        SyntaxKind::DoKeyword => "do",
        SyntaxKind::DotDotDotToken => "...",
        SyntaxKind::DotToken => ".",
        SyntaxKind::ElseKeyword => "else",
        SyntaxKind::EnumKeyword => "enum",
        SyntaxKind::EqualsEqualsEqualsToken => "===",
        SyntaxKind::EqualsEqualsToken => "==",
        SyntaxKind::EqualsGreaterThanToken => "=>",
        SyntaxKind::EqualsToken => "=",
        SyntaxKind::ExclamationEqualsEqualsToken => "!==",
        SyntaxKind::ExclamationEqualsToken => "!=",
        SyntaxKind::ExclamationToken => "!",
        SyntaxKind::ExportKeyword => "export",
        SyntaxKind::ExtendsKeyword => "extends",
        SyntaxKind::FalseKeyword => "false",
        SyntaxKind::FinallyKeyword => "finally",
        SyntaxKind::ForKeyword => "for",
        SyntaxKind::FromKeyword => "from",
        SyntaxKind::FunctionKeyword => "function",
        SyntaxKind::GetKeyword => "get",
        SyntaxKind::GlobalKeyword => "global",
        SyntaxKind::GreaterThanEqualsToken => ">=",
        SyntaxKind::GreaterThanGreaterThanEqualsToken => ">>=",
        SyntaxKind::GreaterThanGreaterThanGreaterThanEqualsToken => ">>>=",
        SyntaxKind::GreaterThanGreaterThanGreaterThanToken => ">>>",
        SyntaxKind::GreaterThanGreaterThanToken => ">>",
        SyntaxKind::GreaterThanToken => ">",
        SyntaxKind::HashToken => "#",
        SyntaxKind::IfKeyword => "if",
        SyntaxKind::ImmediateKeyword => "immediate",
        SyntaxKind::ImplementsKeyword => "implements",
        SyntaxKind::ImportKeyword => "import",
        SyntaxKind::InKeyword => "in",
        SyntaxKind::InferKeyword => "infer",
        SyntaxKind::InstanceOfKeyword => "instanceof",
        SyntaxKind::InterfaceKeyword => "interface",
        SyntaxKind::IntrinsicKeyword => "intrinsic",
        SyntaxKind::IsKeyword => "is",
        SyntaxKind::KeyOfKeyword => "keyof",
        SyntaxKind::LessThanEqualsToken => "<=",
        SyntaxKind::LessThanLessThanEqualsToken => "<<=",
        SyntaxKind::LessThanLessThanToken => "<<",
        SyntaxKind::LessThanSlashToken => "</",
        SyntaxKind::LessThanToken => "<",
        SyntaxKind::LetKeyword => "let",
        SyntaxKind::MinusEqualsToken => "-=",
        SyntaxKind::MinusMinusToken => "--",
        SyntaxKind::MinusToken => "-",
        SyntaxKind::ModuleKeyword => "module",
        SyntaxKind::NamespaceKeyword => "namespace",
        SyntaxKind::NeverKeyword => "never",
        SyntaxKind::NewKeyword => "new",
        SyntaxKind::NullKeyword => "null",
        SyntaxKind::NumberKeyword => "number",
        SyntaxKind::ObjectKeyword => "object",
        SyntaxKind::OfKeyword => "of",
        SyntaxKind::OpenBraceToken => "{",
        SyntaxKind::OpenBracketToken => "[",
        SyntaxKind::OpenParenToken => "(",
        SyntaxKind::OutKeyword => "out",
        SyntaxKind::OverrideKeyword => "override",
        SyntaxKind::PackageKeyword => "package",
        SyntaxKind::PercentEqualsToken => "%=",
        SyntaxKind::PercentToken => "%",
        SyntaxKind::PlusEqualsToken => "+=",
        SyntaxKind::PlusPlusToken => "++",
        SyntaxKind::PlusToken => "+",
        SyntaxKind::PrivateKeyword => "private",
        SyntaxKind::ProtectedKeyword => "protected",
        SyntaxKind::PublicKeyword => "public",
        SyntaxKind::QuestionDotToken => "?.",
        SyntaxKind::QuestionQuestionEqualsToken => "??=",
        SyntaxKind::QuestionQuestionToken => "??",
        SyntaxKind::QuestionToken => "?",
        SyntaxKind::ReadonlyKeyword => "readonly",
        SyntaxKind::RequireKeyword => "require",
        SyntaxKind::ReturnKeyword => "return",
        SyntaxKind::SatisfiesKeyword => "satisfies",
        SyntaxKind::SemicolonToken => ";",
        SyntaxKind::SetKeyword => "set",
        SyntaxKind::SlashEqualsToken => "/=",
        SyntaxKind::SlashToken => "/",
        SyntaxKind::StaticKeyword => "static",
        SyntaxKind::StringKeyword => "string",
        SyntaxKind::SuperKeyword => "super",
        SyntaxKind::SwitchKeyword => "switch",
        SyntaxKind::SymbolKeyword => "symbol",
        SyntaxKind::ThisKeyword => "this",
        SyntaxKind::ThrowKeyword => "throw",
        SyntaxKind::TildeToken => "~",
        SyntaxKind::TrueKeyword => "true",
        SyntaxKind::TryKeyword => "try",
        SyntaxKind::TypeKeyword => "type",
        SyntaxKind::TypeOfKeyword => "typeof",
        SyntaxKind::UndefinedKeyword => "undefined",
        SyntaxKind::UniqueKeyword => "unique",
        SyntaxKind::UnknownKeyword => "unknown",
        SyntaxKind::UsingKeyword => "using",
        SyntaxKind::VarKeyword => "var",
        SyntaxKind::VoidKeyword => "void",
        SyntaxKind::WhileKeyword => "while",
        SyntaxKind::WithKeyword => "with",
        SyntaxKind::YieldKeyword => "yield",
        _ => return None,
    })
}
