//! Keyword lookup, matching TypeScript-Go's `textToKeyword` table.

use crate::ast::SyntaxKind;

/// Returns the keyword kind spelled by `text`, or [`SyntaxKind::Identifier`].
#[must_use]
pub fn identifier_token(text: &str) -> SyntaxKind {
    if !(2..=12).contains(&text.len()) || !text.as_bytes()[0].is_ascii_lowercase() {
        return SyntaxKind::Identifier;
    }
    keyword(text).unwrap_or(SyntaxKind::Identifier)
}

/// Returns the keyword kind spelled by `text`, if any.
#[must_use]
pub fn keyword(text: &str) -> Option<SyntaxKind> {
    Some(match text {
        "abstract" => SyntaxKind::AbstractKeyword,
        "accessor" => SyntaxKind::AccessorKeyword,
        "any" => SyntaxKind::AnyKeyword,
        "as" => SyntaxKind::AsKeyword,
        "assert" => SyntaxKind::AssertKeyword,
        "asserts" => SyntaxKind::AssertsKeyword,
        "async" => SyntaxKind::AsyncKeyword,
        "await" => SyntaxKind::AwaitKeyword,
        "bigint" => SyntaxKind::BigIntKeyword,
        "boolean" => SyntaxKind::BooleanKeyword,
        "break" => SyntaxKind::BreakKeyword,
        "case" => SyntaxKind::CaseKeyword,
        "catch" => SyntaxKind::CatchKeyword,
        "class" => SyntaxKind::ClassKeyword,
        "const" => SyntaxKind::ConstKeyword,
        "constructor" => SyntaxKind::ConstructorKeyword,
        "continue" => SyntaxKind::ContinueKeyword,
        "debugger" => SyntaxKind::DebuggerKeyword,
        "declare" => SyntaxKind::DeclareKeyword,
        "default" => SyntaxKind::DefaultKeyword,
        "defer" => SyntaxKind::DeferKeyword,
        "delete" => SyntaxKind::DeleteKeyword,
        "do" => SyntaxKind::DoKeyword,
        "else" => SyntaxKind::ElseKeyword,
        "enum" => SyntaxKind::EnumKeyword,
        "export" => SyntaxKind::ExportKeyword,
        "extends" => SyntaxKind::ExtendsKeyword,
        "false" => SyntaxKind::FalseKeyword,
        "finally" => SyntaxKind::FinallyKeyword,
        "for" => SyntaxKind::ForKeyword,
        "from" => SyntaxKind::FromKeyword,
        "function" => SyntaxKind::FunctionKeyword,
        "get" => SyntaxKind::GetKeyword,
        "global" => SyntaxKind::GlobalKeyword,
        "if" => SyntaxKind::IfKeyword,
        "immediate" => SyntaxKind::ImmediateKeyword,
        "implements" => SyntaxKind::ImplementsKeyword,
        "import" => SyntaxKind::ImportKeyword,
        "in" => SyntaxKind::InKeyword,
        "infer" => SyntaxKind::InferKeyword,
        "instanceof" => SyntaxKind::InstanceOfKeyword,
        "interface" => SyntaxKind::InterfaceKeyword,
        "intrinsic" => SyntaxKind::IntrinsicKeyword,
        "is" => SyntaxKind::IsKeyword,
        "keyof" => SyntaxKind::KeyOfKeyword,
        "let" => SyntaxKind::LetKeyword,
        "module" => SyntaxKind::ModuleKeyword,
        "namespace" => SyntaxKind::NamespaceKeyword,
        "never" => SyntaxKind::NeverKeyword,
        "new" => SyntaxKind::NewKeyword,
        "null" => SyntaxKind::NullKeyword,
        "number" => SyntaxKind::NumberKeyword,
        "object" => SyntaxKind::ObjectKeyword,
        "of" => SyntaxKind::OfKeyword,
        "out" => SyntaxKind::OutKeyword,
        "override" => SyntaxKind::OverrideKeyword,
        "package" => SyntaxKind::PackageKeyword,
        "private" => SyntaxKind::PrivateKeyword,
        "protected" => SyntaxKind::ProtectedKeyword,
        "public" => SyntaxKind::PublicKeyword,
        "readonly" => SyntaxKind::ReadonlyKeyword,
        "require" => SyntaxKind::RequireKeyword,
        "return" => SyntaxKind::ReturnKeyword,
        "satisfies" => SyntaxKind::SatisfiesKeyword,
        "set" => SyntaxKind::SetKeyword,
        "static" => SyntaxKind::StaticKeyword,
        "string" => SyntaxKind::StringKeyword,
        "super" => SyntaxKind::SuperKeyword,
        "switch" => SyntaxKind::SwitchKeyword,
        "symbol" => SyntaxKind::SymbolKeyword,
        "this" => SyntaxKind::ThisKeyword,
        "throw" => SyntaxKind::ThrowKeyword,
        "true" => SyntaxKind::TrueKeyword,
        "try" => SyntaxKind::TryKeyword,
        "type" => SyntaxKind::TypeKeyword,
        "typeof" => SyntaxKind::TypeOfKeyword,
        "undefined" => SyntaxKind::UndefinedKeyword,
        "unique" => SyntaxKind::UniqueKeyword,
        "unknown" => SyntaxKind::UnknownKeyword,
        "using" => SyntaxKind::UsingKeyword,
        "var" => SyntaxKind::VarKeyword,
        "void" => SyntaxKind::VoidKeyword,
        "while" => SyntaxKind::WhileKeyword,
        "with" => SyntaxKind::WithKeyword,
        "yield" => SyntaxKind::YieldKeyword,
        _ => return None,
    })
}

/// Returns the source spelling of a punctuation or keyword token.
#[must_use]
pub fn token_to_string(kind: SyntaxKind) -> Option<&'static str> {
    punctuation_to_string(kind).or_else(|| all_keywords().find(|text| keyword(text) == Some(kind)))
}

fn punctuation_to_string(kind: SyntaxKind) -> Option<&'static str> {
    Some(match kind {
        SyntaxKind::AmpersandAmpersandEqualsToken => "&&=",
        SyntaxKind::AmpersandAmpersandToken => "&&",
        SyntaxKind::AmpersandEqualsToken => "&=",
        SyntaxKind::AmpersandToken => "&",
        SyntaxKind::AsteriskAsteriskEqualsToken => "**=",
        SyntaxKind::AsteriskAsteriskToken => "**",
        SyntaxKind::AsteriskEqualsToken => "*=",
        SyntaxKind::AsteriskToken => "*",
        SyntaxKind::AtToken => "@",
        SyntaxKind::BacktickToken => "`",
        SyntaxKind::BarBarEqualsToken => "||=",
        SyntaxKind::BarBarToken => "||",
        SyntaxKind::BarEqualsToken => "|=",
        SyntaxKind::BarToken => "|",
        SyntaxKind::CaretEqualsToken => "^=",
        SyntaxKind::CaretToken => "^",
        SyntaxKind::CloseBraceToken => "}",
        SyntaxKind::CloseBracketToken => "]",
        SyntaxKind::CloseParenToken => ")",
        SyntaxKind::ColonToken => ":",
        SyntaxKind::CommaToken => ",",
        SyntaxKind::DotDotDotToken => "...",
        SyntaxKind::DotToken => ".",
        SyntaxKind::EqualsEqualsEqualsToken => "===",
        SyntaxKind::EqualsEqualsToken => "==",
        SyntaxKind::EqualsGreaterThanToken => "=>",
        SyntaxKind::EqualsToken => "=",
        SyntaxKind::ExclamationEqualsEqualsToken => "!==",
        SyntaxKind::ExclamationEqualsToken => "!=",
        SyntaxKind::ExclamationToken => "!",
        SyntaxKind::GreaterThanEqualsToken => ">=",
        SyntaxKind::GreaterThanGreaterThanEqualsToken => ">>=",
        SyntaxKind::GreaterThanGreaterThanGreaterThanEqualsToken => ">>>=",
        SyntaxKind::GreaterThanGreaterThanGreaterThanToken => ">>>",
        SyntaxKind::GreaterThanGreaterThanToken => ">>",
        SyntaxKind::GreaterThanToken => ">",
        SyntaxKind::HashToken => "#",
        SyntaxKind::LessThanEqualsToken => "<=",
        SyntaxKind::LessThanLessThanEqualsToken => "<<=",
        SyntaxKind::LessThanLessThanToken => "<<",
        SyntaxKind::LessThanSlashToken => "</",
        SyntaxKind::LessThanToken => "<",
        SyntaxKind::MinusEqualsToken => "-=",
        SyntaxKind::MinusMinusToken => "--",
        SyntaxKind::MinusToken => "-",
        SyntaxKind::OpenBraceToken => "{",
        SyntaxKind::OpenBracketToken => "[",
        SyntaxKind::OpenParenToken => "(",
        SyntaxKind::PercentEqualsToken => "%=",
        SyntaxKind::PercentToken => "%",
        SyntaxKind::PlusEqualsToken => "+=",
        SyntaxKind::PlusPlusToken => "++",
        SyntaxKind::PlusToken => "+",
        SyntaxKind::QuestionDotToken => "?.",
        SyntaxKind::QuestionQuestionEqualsToken => "??=",
        SyntaxKind::QuestionQuestionToken => "??",
        SyntaxKind::QuestionToken => "?",
        SyntaxKind::SemicolonToken => ";",
        SyntaxKind::SlashEqualsToken => "/=",
        SyntaxKind::SlashToken => "/",
        SyntaxKind::TildeToken => "~",
        _ => return None,
    })
}

/// Returns every keyword spelling in sorted order.
pub fn all_keywords() -> impl Iterator<Item = &'static str> {
    [
        "abstract",
        "accessor",
        "any",
        "as",
        "assert",
        "asserts",
        "async",
        "await",
        "bigint",
        "boolean",
        "break",
        "case",
        "catch",
        "class",
        "const",
        "constructor",
        "continue",
        "debugger",
        "declare",
        "default",
        "defer",
        "delete",
        "do",
        "else",
        "enum",
        "export",
        "extends",
        "false",
        "finally",
        "for",
        "from",
        "function",
        "get",
        "global",
        "if",
        "immediate",
        "implements",
        "import",
        "in",
        "infer",
        "instanceof",
        "interface",
        "intrinsic",
        "is",
        "keyof",
        "let",
        "module",
        "namespace",
        "never",
        "new",
        "null",
        "number",
        "object",
        "of",
        "out",
        "override",
        "package",
        "private",
        "protected",
        "public",
        "readonly",
        "require",
        "return",
        "satisfies",
        "set",
        "static",
        "string",
        "super",
        "switch",
        "symbol",
        "this",
        "throw",
        "true",
        "try",
        "type",
        "typeof",
        "undefined",
        "unique",
        "unknown",
        "using",
        "var",
        "void",
        "while",
        "with",
        "yield",
    ]
    .into_iter()
}
