#!/usr/bin/env node
// Generates src/diagnostics/messages.rs from the pinned TypeScript-Go diagnostic message table.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseArgs } from "node:util";
import { assertPinnedRepository, TYPESCRIPT_GO_REVISION, reportError } from "./typescript-corpus.ts";

interface DiagnosticMessage {
  name: string;
  code: number;
  category: string;
  text: string;
  reportsUnnecessary: boolean;
  elidedInCompatibilityPyramid: boolean;
  reportsDeprecated: boolean;
}

const DECLARATION = /^var (\w+) = &Message\{code: (\d+), category: Category(\w+), key: "(?:[^"\\]|\\.)*", text: ("(?:[^"\\]|\\.)*")(.*)\}$/;

function parseMessages(source: string): DiagnosticMessage[] {
  const messages: DiagnosticMessage[] = [];
  for (const line of source.split("\n")) {
    if (!line.startsWith("var ")) continue;
    const match = DECLARATION.exec(line);
    if (match === null) throw new Error(`Unrecognized diagnostic declaration: ${line}`);
    const flags = match[5];
    messages.push({
      name: match[1],
      code: Number(match[2]),
      category: match[3],
      text: JSON.parse(match[4]) as string,
      reportsUnnecessary: flags.includes("reportsUnnecessary: true"),
      elidedInCompatibilityPyramid: flags.includes("elidedInCompatibilityPyramid: true"),
      reportsDeprecated: flags.includes("reportsDeprecated: true"),
    });
  }
  const names = new Set<string>();
  for (const message of messages) {
    const name = message.name.toUpperCase();
    if (names.has(name)) throw new Error(`Duplicate Rust diagnostic name: ${name}`);
    names.add(name);
  }
  return messages;
}

function rustString(text: string): string {
  let result = "\"";
  for (const character of text) {
    const code = character.codePointAt(0)!;
    if (character === "\\" || character === "\"") result += `\\${character}`;
    else if (character === "\n") result += "\\n";
    else if (character === "\r") result += "\\r";
    else if (character === "\t") result += "\\t";
    else if (code < 0x20) result += `\\u{${code.toString(16)}}`;
    else result += character;
  }
  return `${result}"`;
}

function render(messages: DiagnosticMessage[]): string {
  const constants = messages.map((message) => {
    const flags = [
      message.reportsUnnecessary ? ".reporting_unnecessary()" : "",
      message.elidedInCompatibilityPyramid ? ".elided_in_compatibility_pyramid()" : "",
      message.reportsDeprecated ? ".reporting_deprecated()" : "",
    ].join("");
    return `pub const ${message.name.toUpperCase()}: Message =\n    Message::new(${message.code}, Category::${message.category}, ${rustString(message.text)})${flags};`;
  });
  return `// Code generated by scripts/generate-diagnostic-messages.ts from TypeScript-Go ${TYPESCRIPT_GO_REVISION}. DO NOT EDIT.
#![allow(missing_docs)]

use super::{Category, Message};

${constants.join("\n\n")}
`;
}

function main(): void {
  const { values } = parseArgs({ options: {
    "typescript-go-root": { type: "string" },
    output: { type: "string", default: "src/diagnostics/messages.rs" },
  } });
  const root = values["typescript-go-root"];
  if (root === undefined) throw new Error("--typescript-go-root is required");
  assertPinnedRepository(root, TYPESCRIPT_GO_REVISION, "TypeScript-Go");
  const source = readFileSync(join(root, "internal/diagnostics/diagnostics_generated.go"), "utf8");
  const messages = parseMessages(source);
  writeFileSync(values.output, render(messages));
  console.log(JSON.stringify({ messages: messages.length, output: values.output }));
}

try {
  main();
} catch (error) {
  reportError(error);
}
