#!/usr/bin/env node
// Generates src/ast/flags.rs from the pinned TypeScript-Go token, node, modifier, and symbol flag constants.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseArgs } from "node:util";
import { assertPinnedRepository, TYPESCRIPT_GO_REVISION, reportError } from "./typescript-corpus.ts";

interface FlagSet {
  goType: string;
  file: string;
  doc: string;
}

const FLAG_SETS: FlagSet[] = [
  { goType: "TokenFlags", file: "tokenflags.go", doc: "Flags describing how a token was written." },
  { goType: "NodeFlags", file: "nodeflags.go", doc: "Flags describing a node's syntax and parse context." },
  { goType: "ModifierFlags", file: "modifierflags.go", doc: "Flags summarizing a declaration's modifiers." },
  { goType: "SymbolFlags", file: "symbolflags.go", doc: "Flags classifying the declarations merged into a symbol." },
];

// Evaluates a Go constant expression with Go operator precedence: unary `^`, then
// `<<` and `&`/`&^` (multiplicative), then `|` and `-` (additive).
function evaluate(expression: string, values: Map<string, number>, goType: string): number {
  const tokens = expression.match(/\w+|<<|&\^|[|&^()-]/g) ?? [];
  let index = 0;
  const peek = (): string | undefined => tokens[index];
  const take = (expected?: string): string => {
    const token = tokens[index++];
    if (token === undefined || (expected !== undefined && token !== expected)) {
      throw new Error(`Unexpected token in ${goType} expression: ${expression}`);
    }
    return token;
  };
  const unary = (): number => {
    const token = take();
    if (token === "^") return ~unary() >>> 0;
    if (token === "(") {
      const value = additive();
      take(")");
      return value;
    }
    if (/^\d+$/.test(token)) return Number(token);
    const value = values.get(token.replace(new RegExp(`^${goType}`), ""));
    if (value === undefined) throw new Error(`Unknown ${goType} operand: ${token}`);
    return value;
  };
  const multiplicative = (): number => {
    let value = unary();
    for (let operator = peek(); operator === "<<" || operator === "&" || operator === "&^"; operator = peek()) {
      take();
      const right = unary();
      if (operator === "<<") value = (value << right) >>> 0;
      else if (operator === "&") value = (value & right) >>> 0;
      else value = (value & ~right) >>> 0;
    }
    return value;
  };
  const additive = (): number => {
    let value = multiplicative();
    for (let operator = peek(); operator === "|" || operator === "-"; operator = peek()) {
      take();
      const right = multiplicative();
      value = operator === "|" ? (value | right) >>> 0 : (value - right) >>> 0;
    }
    return value;
  };
  const value = additive();
  if (index !== tokens.length) throw new Error(`Trailing tokens in ${goType} expression: ${expression}`);
  return value;
}

function parseFlags(source: string, goType: string): [string, number][] {
  const block = source.slice(source.indexOf("const ("), source.indexOf("\n)", source.indexOf("const (")));
  const values = new Map<string, number>();
  const flags: [string, number][] = [];
  const declaration = new RegExp(`^${goType}(\\w+)(?:\\s+${goType})?\\s*=\\s*(.+)$`);
  for (const rawLine of block.split("\n")) {
    const line = rawLine.replace(/\/\/.*$/, "").trim();
    const match = declaration.exec(line);
    if (match === null) continue;
    const value = evaluate(match[2], values, goType);
    values.set(match[1], value);
    flags.push([match[1], value]);
  }
  if (flags.length === 0) throw new Error(`No ${goType} constants found`);
  return flags;
}

function constantName(name: string): string {
  return name
    .replace(/JSDoc/g, "Jsdoc")
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .toUpperCase();
}

function render(sets: [FlagSet, [string, number][]][]): string {
  const blocks = sets.map(([set, flags]) => {
    const constants = flags
      .map(([name, value]) => {
        const hex = value.toString(16).padStart(8, "0");
        return `        ${constantName(name)} = 0x${hex.slice(0, 4)}_${hex.slice(4)};`;
      })
      .join("\n");
    return `flags_type! {\n    /// ${set.doc}\n    ${set.goType} {\n${constants}\n    }\n}`;
  });
  return `// Code generated by scripts/generate-ast-flags.ts from TypeScript-Go ${TYPESCRIPT_GO_REVISION}. DO NOT EDIT.

use super::flags_type::flags_type;

${blocks.join("\n\n")}
`;
}

function main(): void {
  const { values } = parseArgs({ options: {
    "typescript-go-root": { type: "string" },
    output: { type: "string", default: "src/ast/flags.rs" },
  } });
  const root = values["typescript-go-root"];
  if (root === undefined) throw new Error("--typescript-go-root is required");
  assertPinnedRepository(root, TYPESCRIPT_GO_REVISION, "TypeScript-Go");
  const sets = FLAG_SETS.map((set): [FlagSet, [string, number][]] => [
    set,
    parseFlags(readFileSync(join(root, "internal/ast", set.file), "utf8"), set.goType),
  ]);
  writeFileSync(values.output, render(sets));
  console.log(JSON.stringify(Object.fromEntries(sets.map(([set, flags]) => [set.goType, flags.length]))));
}

try {
  main();
} catch (error) {
  reportError(error);
}
