#!/usr/bin/env node
// Generates src/check/feature_map.rs from the pinned TypeScript-Go checker feature map, which
// names the lib introducing each global and its members.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseArgs } from "node:util";
import { assertPinnedRepository, TYPESCRIPT_GO_REVISION, reportError } from "./typescript-corpus.ts";

type Feature = [lib: string, props: string[]];

function parseFeatureMap(source: string): [string, Feature[]][] {
  const start = source.indexOf("var getFeatureMap");
  const block = source.slice(start, source.indexOf("\n})", start));
  const sections = block.split(/\n\t\t"(\w+)": \{\n/);
  const result: [string, Feature[]][] = [];
  for (let index = 1; index < sections.length; index += 2) {
    const features = [...sections[index + 1].matchAll(/\{lib: "([^"]+)", props: \[\]string\{([^}]*)\}\}/g)].map(
      (match): Feature => [match[1], [...match[2].matchAll(/"([^"]+)"/g)].map((prop) => prop[1])],
    );
    result.push([sections[index], features]);
  }
  if (result.length === 0) throw new Error("No feature map entries found");
  return result;
}

function render(entries: [string, Feature[]][]): string {
  const rows = entries
    .map(([name, features]) => {
      const libs = features
        .map(([lib, props]) => `(${JSON.stringify(lib)}, &[${props.map((prop) => JSON.stringify(prop)).join(", ")}])`)
        .join(", ");
      return `    (${JSON.stringify(name)}, &[${libs}]),`;
    })
    .join("\n");
  return `// Code generated by scripts/generate-feature-map.ts from TypeScript-Go ${TYPESCRIPT_GO_REVISION}. DO NOT EDIT.

//! The lib that introduces each global and its later members, used to suggest a lib for a
//! missing name or property.

/// A lib and the members of a global it introduces.
pub(super) type LibFeature = (&'static str, &'static [&'static str]);

/// Each global with the libs introducing it and its members, earliest lib first.
const FEATURES: &[(&str, &[LibFeature])] = &[
${rows}
];

/// Returns the libs introducing \`name\` and its members, earliest first.
pub(super) fn features_of(name: &str) -> Option<&'static [LibFeature]> {
    FEATURES
        .iter()
        .find(|(feature, _)| *feature == name)
        .map(|(_, libs)| *libs)
}
`;
}

function main(): void {
  const { values } = parseArgs({ options: {
    "typescript-go-root": { type: "string" },
    output: { type: "string", default: "src/check/feature_map.rs" },
  } });
  const root = values["typescript-go-root"];
  if (root === undefined) throw new Error("--typescript-go-root is required");
  assertPinnedRepository(root, TYPESCRIPT_GO_REVISION, "TypeScript-Go");
  const entries = parseFeatureMap(readFileSync(join(root, "internal/checker/utilities.go"), "utf8"));
  writeFileSync(values.output, render(entries));
  console.log(JSON.stringify({ features: entries.length }));
}

try {
  main();
} catch (error) {
  reportError(error);
}
