#!/usr/bin/env node
// Generates src/ast/kind.rs from the pinned TypeScript-Go `internal/ast/kind_generated.go`.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseArgs } from "node:util";
import { assertPinnedRepository, TYPESCRIPT_GO_REVISION, reportError } from "./typescript-corpus.ts";

interface KindAlias {
  name: string;
  target: string;
}

interface KindTable {
  kinds: string[];
  aliases: KindAlias[];
}

function parseKinds(source: string): KindTable {
  const start = source.indexOf("const (");
  const end = source.indexOf("\n)", start);
  if (start < 0 || end < 0) throw new Error("kind_generated.go has no Kind constant block");
  const kinds: string[] = [];
  const aliases: KindAlias[] = [];
  for (const rawLine of source.slice(start + "const (".length, end).split("\n")) {
    const line = rawLine.replace(/\/\/.*$/, "").trim();
    if (line === "") continue;
    const alias = /^Kind(\w+)\s*=\s*Kind(\w+)$/.exec(line);
    if (alias !== null) {
      aliases.push({ name: alias[1], target: alias[2] });
      continue;
    }
    const kind = /^Kind(\w+)(?:\s+Kind\s*=\s*iota)?$/.exec(line);
    if (kind === null) throw new Error(`Unrecognized Kind declaration: ${rawLine}`);
    kinds.push(kind[1]);
  }
  if (kinds[0] !== "Unknown") throw new Error("Kind enumeration must start with Unknown");
  const known = new Set(kinds);
  const targets = new Map(aliases.map((alias) => [alias.name, alias.target]));
  const resolved = aliases.map((alias) => {
    let target = alias.target;
    const seen = new Set([alias.name]);
    while (targets.has(target) && !seen.has(target)) {
      seen.add(target);
      target = targets.get(target)!;
    }
    if (!known.has(target)) throw new Error(`Alias ${alias.name} targets unknown ${alias.target}`);
    return { name: alias.name, target };
  });
  return { kinds, aliases: resolved };
}

function constantName(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
}

function render({ kinds, aliases }: KindTable): string {
  const variants = kinds.map((kind) => `    ${kind},`).join("\n");
  const constants = aliases
    .map((alias) => `    /// Alias of [\`SyntaxKind::${alias.target}\`].\n    pub const ${constantName(alias.name)}: Self = Self::${alias.target};`)
    .join("\n");
  return `// Code generated by scripts/generate-syntax-kinds.ts from TypeScript-Go ${TYPESCRIPT_GO_REVISION}. DO NOT EDIT.

/// Token and node kinds, in TypeScript-Go declaration order.
#[allow(missing_docs)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u16)]
pub enum SyntaxKind {
${variants}
}

#[allow(missing_docs)]
impl SyntaxKind {
${constants}
}
`;
}

function main(): void {
  const { values } = parseArgs({ options: {
    "typescript-go-root": { type: "string" },
    output: { type: "string", default: "src/ast/kind.rs" },
  } });
  const root = values["typescript-go-root"];
  if (root === undefined) throw new Error("--typescript-go-root is required");
  assertPinnedRepository(root, TYPESCRIPT_GO_REVISION, "TypeScript-Go");
  const source = readFileSync(join(root, "internal/ast/kind_generated.go"), "utf8");
  const table = parseKinds(source);
  writeFileSync(values.output, render(table));
  console.log(JSON.stringify({ kinds: table.kinds.length, aliases: table.aliases.length, output: values.output }));
}

try {
  main();
} catch (error) {
  reportError(error);
}
