#!/usr/bin/env node
// Generates src/scanner/identifier_tables.rs from the pinned TypeScript-Go Unicode identifier tables.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseArgs } from "node:util";
import { assertPinnedRepository, TYPESCRIPT_GO_REVISION, reportError } from "./typescript-corpus.ts";

type Range = [low: number, high: number, stride: number];

function parseTable(source: string, name: string): Range[] {
  const start = source.indexOf(`var ${name} = &unicode.RangeTable{`);
  if (start < 0) throw new Error(`Missing range table ${name}`);
  const end = source.indexOf("\n}", start);
  const ranges: Range[] = [];
  for (const match of source.slice(start, end).matchAll(/\{(0x[0-9A-F]+), (0x[0-9A-F]+), (\d+)\}/g)) {
    ranges.push([Number(match[1]), Number(match[2]), Number(match[3])]);
  }
  for (let index = 1; index < ranges.length; index++) {
    if (ranges[index][0] <= ranges[index - 1][1]) throw new Error(`${name} ranges are not sorted at ${index}`);
  }
  if (ranges.length === 0) throw new Error(`Range table ${name} is empty`);
  return ranges;
}

function hex(value: number): string {
  return `0x${value.toString(16).toUpperCase()}`;
}

function renderTable(name: string, ranges: Range[]): string {
  const rows = ranges.map(([low, high, stride]) => `    (${hex(low)}, ${hex(high)}, ${stride}),`).join("\n");
  return `pub(super) const ${name}: &[(u32, u32, u32)] = &[\n${rows}\n];`;
}

function main(): void {
  const { values } = parseArgs({ options: {
    "typescript-go-root": { type: "string" },
    output: { type: "string", default: "src/scanner/identifier_tables.rs" },
  } });
  const root = values["typescript-go-root"];
  if (root === undefined) throw new Error("--typescript-go-root is required");
  assertPinnedRepository(root, TYPESCRIPT_GO_REVISION, "TypeScript-Go");
  const path = join(root, "internal/stringutil/identifier_parts_generated.go");
  const source = readFileSync(path, "utf8");
  const version = /Unicode (\d+\.\d+\.\d+)/.exec(source)?.[1];
  if (version === undefined) throw new Error("Identifier tables do not name a Unicode version");
  const start = parseTable(source, "unicodeESNextIdentifierStart");
  const part = parseTable(source, "unicodeESNextIdentifierPart");
  writeFileSync(values.output, `// Code generated by scripts/generate-identifier-tables.ts from TypeScript-Go ${TYPESCRIPT_GO_REVISION}. DO NOT EDIT.
// Unicode ${version} ECMAScript identifier ranges as (low, high, stride).

${renderTable("IDENTIFIER_START", start)}

${renderTable("IDENTIFIER_PART", part)}
`);
  console.log(JSON.stringify({ unicode: version, start: start.length, part: part.length, output: values.output }));
}

try {
  main();
} catch (error) {
  reportError(error);
}
