#!/usr/bin/env node
// Copies the pinned TypeScript-Go bundled lib declaration files into libs/ and generates
// src/bundled/mod.rs, which embeds them in the compiler as TypeScript-Go embeds them in tsgo.
import { copyFileSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseArgs } from "node:util";
import { assertPinnedRepository, TYPESCRIPT_GO_REVISION, reportError } from "./typescript-corpus.ts";

// Reads the `lib` compiler option names and their files from TypeScript-Go's LibMap.
function parseLibMap(source: string): [string, string][] {
  const block = source.slice(source.indexOf("var LibMap"), source.indexOf("\n})", source.indexOf("var LibMap")));
  const entries = [...block.matchAll(/\{Key: "([^"]+)", Value: "([^"]+)"\}/g)].map((match): [string, string] => [match[1], match[2]]);
  if (entries.length === 0) throw new Error("No LibMap entries found");
  return entries;
}

// Reads the default lib file of each target, keyed by the target's option name.
function parseTargetLibs(source: string): [string, string][] {
  const block = source.slice(source.indexOf("var targetToLibMap"), source.indexOf("\n}", source.indexOf("var targetToLibMap")));
  const entries = [...block.matchAll(/core\.ScriptTarget(\w+):\s*"([^"]+)"/g)].map((match): [string, string] => [match[1].toLowerCase(), match[2]]);
  if (entries.length === 0) throw new Error("No targetToLibMap entries found");
  return entries;
}

function render(names: string[], libMap: [string, string][], targetLibs: [string, string][]): string {
  const options = libMap.map(([option, file]) => `    ("${option}", "${file}"),`).join("\n");
  const targets = targetLibs.map(([target, file]) => `    ("${target}", "${file}"),`).join("\n");
  const entries = names.map((name) => `    ("${name}", include_str!("../../libs/${name}")),`).join("\n");
  return `// Code generated by scripts/vendor-typescript-libs.ts from TypeScript-Go ${TYPESCRIPT_GO_REVISION}. DO NOT EDIT.

//! The TypeScript standard library declaration files, embedded as TypeScript-Go bundles them.
//!
//! The files are Copyright (c) Microsoft Corporation and licensed under the Apache License 2.0;
//! each file carries its own notice.

/// Every bundled lib file name with its text, sorted by name.
const LIBS: &[(&str, &str)] = &[
${entries}
];

/// Each \`lib\` compiler option name with its file, in TypeScript-Go's load order.
const LIB_OPTIONS: &[(&str, &str)] = &[
${options}
];

/// Each target option name with the lib file loaded by default for it.
const TARGET_DEFAULT_LIBS: &[(&str, &str)] = &[
${targets}
];

/// Returns every bundled lib file name, sorted by name.
#[must_use]
pub fn lib_names() -> Vec<&'static str> {
    LIBS.iter().map(|(name, _)| *name).collect()
}

/// Returns the text of the bundled lib file \`name\`, such as \`lib.es5.d.ts\`.
#[must_use]
pub fn lib_text(name: &str) -> Option<&'static str> {
    LIBS.binary_search_by(|(candidate, _)| (*candidate).cmp(name))
        .ok()
        .map(|index| LIBS[index].1)
}

/// Returns the lib file named by a \`lib\` compiler option value, such as \`es2015.promise\`.
#[must_use]
pub fn lib_file_for_option(option: &str) -> Option<&'static str> {
    LIB_OPTIONS
        .iter()
        .find(|(name, _)| *name == option)
        .map(|(_, file)| *file)
}

/// Returns every \`lib\` option name in TypeScript-Go's order.
#[must_use]
pub fn lib_option_names() -> Vec<&'static str> {
    LIB_OPTIONS.iter().map(|(name, _)| *name).collect()
}

/// Returns the lib file for a \`lib\` option value or lib file name, compared case-insensitively.
#[must_use]
pub fn lib_file_name(name: &str) -> Option<&'static str> {
    let name = name.to_ascii_lowercase();
    LIB_OPTIONS
        .iter()
        .find(|(_, file)| *file == name)
        .map(|(_, file)| *file)
        .or_else(|| lib_file_for_option(&name))
}

/// Returns where a lib file sorts among a program's libs: \`lib.d.ts\` and \`lib.es6.d.ts\` first,
/// then libs in \`lib\` option order, then any other file.
#[must_use]
pub fn lib_priority(file_name: &str) -> usize {
    if file_name == "lib.d.ts" || file_name == "lib.es6.d.ts" {
        return 0;
    }
    let name = file_name
        .strip_prefix("lib.")
        .and_then(|name| name.strip_suffix(".d.ts"))
        .unwrap_or(file_name);
    LIB_OPTIONS
        .iter()
        .position(|(option, _)| *option == name)
        .map_or(LIB_OPTIONS.len() + 2, |index| index + 1)
}

/// Returns the lib file loaded by default for a target option name, such as \`es2022\`; targets
/// before ES2015 load \`lib.d.ts\`.
#[must_use]
pub fn default_lib_file_name(target: &str) -> &'static str {
    TARGET_DEFAULT_LIBS
        .iter()
        .find(|(name, _)| *name == target)
        .map_or("lib.d.ts", |(_, file)| *file)
}
`;
}

function main(): void {
  const { values } = parseArgs({ options: {
    "typescript-go-root": { type: "string" },
    "libs-output": { type: "string", default: "libs" },
    "module-output": { type: "string", default: "src/bundled/mod.rs" },
  } });
  const root = values["typescript-go-root"];
  if (root === undefined) throw new Error("--typescript-go-root is required");
  assertPinnedRepository(root, TYPESCRIPT_GO_REVISION, "TypeScript-Go");
  const source = join(root, "internal/bundled/libs");
  const names = readdirSync(source).filter((name) => name.endsWith(".d.ts")).sort();
  const output = values["libs-output"];
  rmSync(output, { recursive: true, force: true });
  mkdirSync(output, { recursive: true });
  for (const name of names) copyFileSync(join(source, name), join(output, name));
  mkdirSync(join(values["module-output"], ".."), { recursive: true });
  const enumMaps = readFileSync(join(root, "internal/tsoptions/enummaps.go"), "utf8");
  writeFileSync(values["module-output"], render(names, parseLibMap(enumMaps), parseTargetLibs(enumMaps)));
  console.log(JSON.stringify({ libs: names.length }));
}

try {
  main();
} catch (error) {
  reportError(error);
}
