#!/usr/bin/env node
// Copies the pinned TypeScript-Go bundled lib declaration files into libs/ and generates
// src/bundled/mod.rs, which embeds them in the compiler as TypeScript-Go embeds them in tsgo.
import { copyFileSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseArgs } from "node:util";
import { assertPinnedRepository, TYPESCRIPT_GO_REVISION, reportError } from "./typescript-corpus.ts";

function render(names: string[]): string {
  const entries = names.map((name) => `    ("${name}", include_str!("../../libs/${name}")),`).join("\n");
  return `// Code generated by scripts/vendor-typescript-libs.ts from TypeScript-Go ${TYPESCRIPT_GO_REVISION}. DO NOT EDIT.

//! The TypeScript standard library declaration files, embedded as TypeScript-Go bundles them.
//!
//! The files are Copyright (c) Microsoft Corporation and licensed under the Apache License 2.0;
//! each file carries its own notice.

/// Every bundled lib file name with its text, sorted by name.
const LIBS: &[(&str, &str)] = &[
${entries}
];

/// Returns every bundled lib file name, sorted by name.
#[must_use]
pub fn lib_names() -> Vec<&'static str> {
    LIBS.iter().map(|(name, _)| *name).collect()
}

/// Returns the text of the bundled lib file \`name\`, such as \`lib.es5.d.ts\`.
#[must_use]
pub fn lib_text(name: &str) -> Option<&'static str> {
    LIBS.binary_search_by(|(candidate, _)| (*candidate).cmp(name))
        .ok()
        .map(|index| LIBS[index].1)
}
`;
}

function main(): void {
  const { values } = parseArgs({ options: {
    "typescript-go-root": { type: "string" },
    "libs-output": { type: "string", default: "libs" },
    "module-output": { type: "string", default: "src/bundled/mod.rs" },
  } });
  const root = values["typescript-go-root"];
  if (root === undefined) throw new Error("--typescript-go-root is required");
  assertPinnedRepository(root, TYPESCRIPT_GO_REVISION, "TypeScript-Go");
  const source = join(root, "internal/bundled/libs");
  const names = readdirSync(source).filter((name) => name.endsWith(".d.ts")).sort();
  const output = values["libs-output"];
  rmSync(output, { recursive: true, force: true });
  mkdirSync(output, { recursive: true });
  for (const name of names) copyFileSync(join(source, name), join(output, name));
  mkdirSync(join(values["module-output"], ".."), { recursive: true });
  writeFileSync(values["module-output"], render(names));
  console.log(JSON.stringify({ libs: names.length }));
}

try {
  main();
} catch (error) {
  reportError(error);
}
